name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests
      run: mvn test

    - name: Execute Java program
      run: java -cp target/classes Task_1

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: java-results
        path: target/surefire-reports/
